<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $protocol->title }} - HomeHeal</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            color: #1e293b;
            line-height: 1.6;
            margin: 20px;
        }
        .header {
            border-bottom: 3px solid #10b981;
            padding-bottom: 15px;
            margin-bottom: 20px;
        }
        .header h1 {
            color: #10b981;
            margin: 0 0 5px 0;
        }
        .meta {
            color: #64748b;
            font-size: 14px;
        }
        .section {
            margin-bottom: 25px;
        }
        .section-title {
            background: #f1f5f9;
            padding: 8px 12px;
            font-weight: bold;
            color: #0f172a;
            margin-bottom: 10px;
        }
        .exercise {
            border-left: 3px solid #14b8a6;
            padding-left: 15px;
            margin-bottom: 20px;
        }
        .exercise-title {
            font-size: 18px;
            font-weight: bold;
            color: #0f172a;
            margin-bottom: 5px;
        }
        .exercise-meta {
            color: #64748b;
            font-size: 14px;
            margin-bottom: 8px;
        }
        .exercise-instructions {
            color: #475569;
            white-space: pre-line;
        }
        .badge {
            background: #fbbf24;
            color: #78350f;
            padding: 3px 8px;
            border-radius: 4px;
            font-size: 12px;
            display: inline-block;
            margin: 2px;
        }
        .footer {
            margin-top: 40px;
            padding-top: 15px;
            border-top: 1px solid #e2e8f0;
            text-align: center;
            color: #94a3b8;
            font-size: 12px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $protocol->title }}</h1>
        <div class="meta">
            Created by: {{ $protocol->therapist->name }}<br>
            Date: {{ $protocol->created_at->format('F j, Y') }}
        </div>
    </div>

    <div class="section">
        <div class="section-title">Description</div>
        <p>{{ $protocol->description }}</p>
    </div>

    <div class="section">
        <div class="section-title">Prescribed Exercises</div>
        
        @foreach($protocol->exercises as $index => $exercise)
            <div class="exercise">
                <div class="exercise-title">{{ $index + 1 }}. {{ $exercise->name }}</div>
                
                <div class="exercise-meta">
                    <strong>Prescription:</strong> 
                    {{ $exercise->pivot->sets }} sets × {{ $exercise->pivot->reps }} reps
                    @if($exercise->pivot->rest_seconds)
                        • {{ $exercise->pivot->rest_seconds }}s rest
                    @endif
                </div>

                <div class="exercise-instructions">
                    <strong>Instructions:</strong><br>
                    {{ $exercise->instructions }}
                </div>
            </div>
        @endforeach
    </div>

    <div class="footer">
        Generated by HomeHeal • {{ now()->format('F j, Y g:i A') }}
    </div>
</body>
</html>
